### ISSUE TITLE
println missing from website

### ISSUE THREAD

**Issue by planet36** [fmtlib/fmt.dev#24]
`println` is not documented on the fmt.dev website.

This query returns no results.
https://fmt.dev/latest/search.html?q=println

**Comment by vitaut** [comment]
Same as https://github.com/fmtlib/fmt/issues/3775.

**Comment by planet36** [comment]
Is fmt.dev the official online documentation of fmtlib?
If I search on https://fmt.dev/latest/api.html for "println", there's no match.
Does it need to be re-generated?

**Comment by vitaut** [comment]
> Is fmt.dev the official online documentation of fmtlib?

Yes

> Does it need to be re-generated?

The `println` docs are in the dev version: https://fmt.dev/dev/api.html. They will make their way to the latest once released.
